version: '3.8'

services:
  frontend:
    image: ibrahimelnemr/one-pager-search-engine-frontend:latest
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://backend:5000
