version: '3.8'

services:
  backend:
    image: ibrahimelnemr/one-pager-search-engine-backend:latest
    ports:
      - "5050:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - ELASTICSEARCH_HOST=http://localhost:9200
